/* v039_127 key/main story config scaffold */
(function(){
  "use strict";
  const empty = function(name, title){ return { characterName: name, requiredStories: [], slotStories: {}, completeReward: { title } }; };
  window.TENOTSU_KEY_STORY_CONFIG = {
    aa: empty("星野 緋奈", "緋奈との絆"),
    ab: empty("速水川 藍", "藍との絆"),
    ac: empty("草壁 翠", "翠との絆"),
    ad: empty("小麦沢 こがね", "こがねとの絆"),
    ae: empty("春日原 琥珀", "琥珀との絆"),
    af: empty("大道寺 真花", "真花との絆"),
    ag: empty("氷神 雪乃", "雪乃との絆"),
    ah: empty("双沢 美空", "美空との絆"),
    ai: {
      characterName: "双沢 夜空",
      requiredStories: [
        "yozora_affection_00_01_key",
        "yozora_affection_00_02_key",
        "yozora_affection_00_03_key",
        "yozora_affection_10_01_key",
        "yozora_affection_10_02_key",
        "yozora_affection_10_03_key",
        "yozora_affection_20_01_key",
        "yozora_affection_20_02_key",
        "yozora_affection_20_03_key",
        "yozora_affection_30_01_key",
        "yozora_affection_30_02_key",
        "yozora_affection_30_03_key",
        "yozora_affection_40_01_key",
        "yozora_affection_40_02_key",
        "yozora_affection_40_03_key",
        "yozora_affection_50_01_key",
        "yozora_affection_50_02_key",
        "yozora_affection_50_03_key",
        "yozora_affection_60_01_key",
        "yozora_affection_60_02_key",
        "yozora_affection_60_03_key",
        "yozora_affection_70_01_key",
        "yozora_affection_70_02_key",
        "yozora_affection_70_03_key",
        "yozora_affection_80_01_key",
        "yozora_affection_80_02_key",
        "yozora_affection_80_03_key",
        "yozora_affection_90_01_key",
        "yozora_affection_90_02_key",
        "yozora_affection_90_03_key"
      ],
      slotStories: {
        b1_key1: "yozora_affection_00_01_key",
        b1_key2: "yozora_affection_00_02_key",
        b1_key3: "yozora_affection_00_03_key",
        b1_main: "yozora_affection_10_00_main",
        b2_key1: "yozora_affection_10_01_key",
        b2_key2: "yozora_affection_10_02_key",
        b2_key3: "yozora_affection_10_03_key",
        b2_main: "yozora_affection_20_00_main",
        b3_key1: "yozora_affection_20_01_key",
        b3_key2: "yozora_affection_20_02_key",
        b3_key3: "yozora_affection_20_03_key",
        b3_main: "yozora_affection_30_00_main",
        b4_key1: "yozora_affection_30_01_key",
        b4_key2: "yozora_affection_30_02_key",
        b4_key3: "yozora_affection_30_03_key",
        b4_main: "yozora_affection_40_00_main",
        b5_key1: "yozora_affection_40_01_key",
        b5_key2: "yozora_affection_40_02_key",
        b5_key3: "yozora_affection_40_03_key",
        b5_main: "yozora_affection_50_00_main",
        b6_key1: "yozora_affection_50_01_key",
        b6_key2: "yozora_affection_50_02_key",
        b6_key3: "yozora_affection_50_03_key",
        b6_main: "yozora_affection_60_00_main",
        b7_key1: "yozora_affection_60_01_key",
        b7_key2: "yozora_affection_60_02_key",
        b7_key3: "yozora_affection_60_03_key",
        b7_main: "yozora_affection_70_00_main",
        b8_key1: "yozora_affection_70_01_key",
        b8_key2: "yozora_affection_70_02_key",
        b8_key3: "yozora_affection_70_03_key",
        b8_main: "yozora_affection_80_00_main",
        b9_key1: "yozora_affection_80_01_key",
        b9_key2: "yozora_affection_80_02_key",
        b9_key3: "yozora_affection_80_03_key",
        b9_main: "yozora_affection_90_00_main",
        b10_key1: "yozora_affection_90_01_key",
        b10_key2: "yozora_affection_90_02_key",
        b10_key3: "yozora_affection_90_03_key",
        b10_main: "yozora_affection_100_00_main"
      },
      completeReward: { title: "夜空との絆" }
    },
    aj: empty("芝桜 桃", "桃との絆"),
    ak: empty("紫藤 彩愛", "彩愛との絆"),
    al: empty("餅月 里美", "里美との絆"),
    am: empty("草壁 萌", "萌との絆"),
    ba: empty("天神 小春", "小春との因縁"),
    bb: empty("霧島 真冬", "真冬との信頼"),
    bc: empty("日向 なつ", "なつとの縁")
  };
})();
